# Generated by Django 2.1.7 on 2019-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_semi_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('AE', 'Academic English'), ('IT', 'Information Technology'), ('BS', 'Behavioural Science'), ('MA', 'Mathematics'), ('CH', 'Chemistry'), ('PH', 'Physics'), ('AR', 'Architecture'), ('RE', 'Research'), ('AC', 'Accounting')], max_length=2, unique=True),
        ),
    ]
