# Generated by Django 2.1.7 on 2019-04-29 19:20

from django.db import migrations, models
import isp_semi_auto.models


class Migration(migrations.Migration):

    dependencies = [
        ('isp_semi_auto', '0002_auto_20190329_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttemplate',
            name='template',
            field=models.TextField(blank=True, help_text='Paste template here', null=True),
        ),
        migrations.AlterField(
            model_name='subjecttemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Upload template here', null=True, upload_to=isp_semi_auto.models.template_path),
        ),
    ]
